// This file is auto-generated by genIpcHandlers, any changes will be lost

import { ipcMain } from "electron";
import { getConfig, getConfigBulk, getDefaultValue, loadConfig, setConfig, setConfigBulk } from "../config";
import { setAutoLaunchState } from "../loader";
import { initArrpc } from "../modules/arrpc";
import { getAssets } from "../modules/assetLoader";
import { clearCache } from "../modules/cacheManager";
import { setBadgeCount } from "../modules/dynamicIcon";
import { i } from "../modules/localization";
import { cycleThroughPasswords, decryptMessage, encryptMessage } from "../modules/messageEncryption";
import { updateModsFull } from "../modules/mods";
import { isVenbindLoaded, setKeybinds } from "../modules/venbind";
import { stopVenmic } from "../modules/venmic";
import { decryptSafeStorage, encryptSafeStorage, getDisplayVersion, getVersion, isEncryptionAvailable, saveFileToGCFolder } from "../utils";
import { deleteCloud, loadCloud, saveCloud } from "../windows/settings/preload/cloud/cloud";
import { createSettingsWindow, hotreloadLocale, reloadWindow } from "../windows/settings/settings";

export function registerAllHandlers() {
  ipcMain.handle("arrpc:initArrpc", async (event) => { return await initArrpc(); });
  ipcMain.on("assetLoader:getAssets", (event) => { event.returnValue = getAssets(); });
  ipcMain.handle("cacheManager:clearCache", async (event) => { return await clearCache(); });
  ipcMain.handle("cloud:deleteCloud", async (event) => { return await deleteCloud(); });
  ipcMain.handle("cloud:loadCloud", async (event) => { return await loadCloud(); });
  ipcMain.handle("cloud:saveCloud", async (event, silent) => { return await saveCloud(silent); });
  ipcMain.on("config:getConfig", (event, key, bypassDefault) => { event.returnValue = getConfig(key, bypassDefault); });
  ipcMain.on("config:getConfigBulk", (event) => { event.returnValue = getConfigBulk(); });
  ipcMain.on("config:getDefaultValue", (event, entry) => { event.returnValue = getDefaultValue(entry); });
  ipcMain.handle("config:loadConfig", async (event) => { return await loadConfig(); });
  ipcMain.handle("config:setConfig", async (event, entry, value) => { return await setConfig(entry, value); });
  ipcMain.handle("config:setConfigBulk", async (event, toSet) => { return await setConfigBulk(toSet); });
  ipcMain.handle("dynamicIcon:setBadgeCount", async (event, requestedCount) => { return await setBadgeCount(requestedCount); });
  ipcMain.handle("loader:setAutoLaunchState", async (event) => { return await setAutoLaunchState(); });
  ipcMain.on("localization:i", (event, key) => { event.returnValue = i(key); });
  ipcMain.handle("messageEncryption:cycleThroughPasswords", (event) => { return cycleThroughPasswords(); });
  ipcMain.on("messageEncryption:decryptMessage", (event, message) => { event.returnValue = decryptMessage(message); });
  ipcMain.on("messageEncryption:encryptMessage", (event, message) => { event.returnValue = encryptMessage(message); });
  ipcMain.handle("mods:updateModsFull", async (event) => { return await updateModsFull(); });
  ipcMain.handle("settings:createSettingsWindow", async (event) => { return await createSettingsWindow(); });
  ipcMain.handle("settings:hotreloadLocale", async (event) => { return await hotreloadLocale(); });
  ipcMain.handle("settings:reloadWindow", async (event) => { return await reloadWindow(); });
  ipcMain.on("utils:decryptSafeStorage", (event, encryptedBase64) => { event.returnValue = decryptSafeStorage(encryptedBase64); });
  ipcMain.on("utils:encryptSafeStorage", (event, plaintextString) => { event.returnValue = encryptSafeStorage(plaintextString); });
  ipcMain.on("utils:getDisplayVersion", (event) => { event.returnValue = getDisplayVersion(); });
  ipcMain.on("utils:getVersion", (event) => { event.returnValue = getVersion(); });
  ipcMain.on("utils:isEncryptionAvailable", (event) => { event.returnValue = isEncryptionAvailable(); });
  ipcMain.handle("utils:saveFileToGCFolder", async (event, filePath, content) => { return await saveFileToGCFolder(filePath, content); });
  ipcMain.handle("venbind:isVenbindLoaded", async (event) => { return await isVenbindLoaded(); });
  ipcMain.handle("venbind:setKeybinds", async (event, keybinds) => { return await setKeybinds(keybinds); });
  ipcMain.handle("venmic:stopVenmic", (event) => { return stopVenmic(); });
}
