// This file is auto-generated by genIpcHandlers, any changes will be lost

import type { getConfig as ___config_getConfig, getDefaultValue as ___config_getDefaultValue, loadConfig as ___config_loadConfig, setConfig as ___config_setConfig, setConfigBulk as ___config_setConfigBulk, sync as ___config_sync } from "../config";
import type { setAutoLaunchState as ___loader_setAutoLaunchState } from "../loader";
import type { initArrpc as ___modules_arrpc_initArrpc } from "../modules/arrpc";
import type { getAssets as ___modules_assetLoader_getAssets } from "../modules/assetLoader";
import type { clearCache as ___modules_cacheManager_clearCache } from "../modules/cacheManager";
import type { setBadgeCount as ___modules_dynamicIcon_setBadgeCount } from "../modules/dynamicIcon";
import type { sync as ___modules_localization_localization_main_sync } from "../modules/localization/localization.main";
import type { cycleThroughPasswords as ___modules_messageEncryption_cycleThroughPasswords, decryptMessage as ___modules_messageEncryption_decryptMessage, encryptMessage as ___modules_messageEncryption_encryptMessage } from "../modules/messageEncryption";
import type { updateModsFull as ___modules_mods_updateModsFull } from "../modules/mods";
import type { isVenbindLoaded as ___modules_venbind_isVenbindLoaded, setKeybinds as ___modules_venbind_setKeybinds } from "../modules/venbind";
import type { stopVenmic as ___modules_venmic_stopVenmic } from "../modules/venmic";
import type { decryptSafeStorage as ___utils_decryptSafeStorage, encryptSafeStorage as ___utils_encryptSafeStorage, getDisplayVersion as ___utils_getDisplayVersion, getVersion as ___utils_getVersion, isEncryptionAvailable as ___utils_isEncryptionAvailable, saveFileToGCFolder as ___utils_saveFileToGCFolder } from "../utils";
import type { createQuickCssWindow as ___windows_main_quickCssFix_createQuickCssWindow } from "../windows/main/quickCssFix";
import type { deleteCloud as ___windows_settings_cloud_cloud_deleteCloud, loadCloud as ___windows_settings_cloud_cloud_loadCloud, saveCloud as ___windows_settings_cloud_cloud_saveCloud } from "../windows/settings/cloud/cloud";
import type { createSettingsWindow as ___windows_settings_settings_createSettingsWindow, hotreloadLocale as ___windows_settings_settings_hotreloadLocale, reloadWindow as ___windows_settings_settings_reloadWindow } from "../windows/settings/settings";

export interface IpcHandleChannels {
  "arrpc:initArrpc": typeof ___modules_arrpc_initArrpc;
  "cacheManager:clearCache": typeof ___modules_cacheManager_clearCache;
  "cloud:deleteCloud": typeof ___windows_settings_cloud_cloud_deleteCloud;
  "cloud:loadCloud": typeof ___windows_settings_cloud_cloud_loadCloud;
  "cloud:saveCloud": typeof ___windows_settings_cloud_cloud_saveCloud;
  "config:loadConfig": typeof ___config_loadConfig;
  "config:setConfig": typeof ___config_setConfig;
  "config:setConfigBulk": typeof ___config_setConfigBulk;
  "dynamicIcon:setBadgeCount": typeof ___modules_dynamicIcon_setBadgeCount;
  "loader:setAutoLaunchState": typeof ___loader_setAutoLaunchState;
  "messageEncryption:cycleThroughPasswords": typeof ___modules_messageEncryption_cycleThroughPasswords;
  "mods:updateModsFull": typeof ___modules_mods_updateModsFull;
  "quickCssFix:createQuickCssWindow": typeof ___windows_main_quickCssFix_createQuickCssWindow;
  "settings:createSettingsWindow": typeof ___windows_settings_settings_createSettingsWindow;
  "settings:hotreloadLocale": typeof ___windows_settings_settings_hotreloadLocale;
  "settings:reloadWindow": typeof ___windows_settings_settings_reloadWindow;
  "utils:saveFileToGCFolder": typeof ___utils_saveFileToGCFolder;
  "venbind:isVenbindLoaded": typeof ___modules_venbind_isVenbindLoaded;
  "venbind:setKeybinds": typeof ___modules_venbind_setKeybinds;
  "venmic:stopVenmic": typeof ___modules_venmic_stopVenmic;
}

export interface IpcOnChannels {
  "assetLoader:getAssets": typeof ___modules_assetLoader_getAssets;
  "config:getConfig": typeof ___config_getConfig;
  "config:getDefaultValue": typeof ___config_getDefaultValue;
  "config:sync": typeof ___config_sync;
  "localization:sync": typeof ___modules_localization_localization_main_sync;
  "messageEncryption:decryptMessage": typeof ___modules_messageEncryption_decryptMessage;
  "messageEncryption:encryptMessage": typeof ___modules_messageEncryption_encryptMessage;
  "utils:decryptSafeStorage": typeof ___utils_decryptSafeStorage;
  "utils:encryptSafeStorage": typeof ___utils_encryptSafeStorage;
  "utils:getDisplayVersion": typeof ___utils_getDisplayVersion;
  "utils:getVersion": typeof ___utils_getVersion;
  "utils:isEncryptionAvailable": typeof ___utils_isEncryptionAvailable;
}

export interface RegisteredIpcHandleChannels {
  "flashTitlebar": (color: string) => void;
  "flashTitlebarWithText": (color: string, text: string) => void;
  "invidiousConfigChanged": () => void;
  "openFolder": (folder: string) => void;
  "window:Close": () => void;
  "window:Hide": () => void;
  "window:IsMaximized": () => void;
  "window:Maximize": () => void;
  "window:Minimize": () => void;
  "window:Show": () => void;
  "window:Unmaximize": () => void;
}

export interface RegisteredIpcOnChannels {
}

export type AllIpcHandleChannels = IpcHandleChannels & RegisteredIpcHandleChannels;
export type AllIpcOnChannels = IpcOnChannels & RegisteredIpcOnChannels;
export type AllIpcChannels = AllIpcHandleChannels & AllIpcOnChannels;

export type IpcHandleChannel = keyof AllIpcHandleChannels;
export type IpcOnChannel = keyof AllIpcOnChannels;
export type IpcChannel = keyof AllIpcChannels;

export type IpcParams<T extends IpcChannel> = Parameters<AllIpcChannels[T]>;
export type IpcReturn<T extends IpcChannel> = ReturnType<AllIpcChannels[T]>;

// Utility type for awaited return values
export type IpcReturnAwaited<T extends IpcChannel> = Awaited<IpcReturn<T>>;
