// This file is auto-generated by genIpcHandlers, any changes will be lost

import type { getConfig, getConfigBulk, getDefaultValue, loadConfig, setConfig, setConfigBulk } from "../config";
import type { setAutoLaunchState } from "../loader";
import type { initArrpc } from "../modules/arrpc";
import type { getAssets } from "../modules/assetLoader";
import type { clearCache } from "../modules/cacheManager";
import type { setBadgeCount } from "../modules/dynamicIcon";
import type { i } from "../modules/localization";
import type { cycleThroughPasswords, decryptMessage, encryptMessage } from "../modules/messageEncryption";
import type { updateModsFull } from "../modules/mods";
import type { isVenbindLoaded, setKeybinds } from "../modules/venbind";
import type { stopVenmic } from "../modules/venmic";
import type { decryptSafeStorage, encryptSafeStorage, getDisplayVersion, getVersion, isEncryptionAvailable, saveFileToGCFolder } from "../utils";
import type { deleteCloud, loadCloud, saveCloud } from "../windows/settings/preload/cloud/cloud";
import type { createSettingsWindow, hotreloadLocale } from "../windows/settings/settings";

export interface IpcHandleChannels {
  "arrpc:initArrpc": typeof initArrpc;
  "cacheManager:clearCache": typeof clearCache;
  "cloud:deleteCloud": typeof deleteCloud;
  "cloud:loadCloud": typeof loadCloud;
  "cloud:saveCloud": typeof saveCloud;
  "config:loadConfig": typeof loadConfig;
  "config:setConfig": typeof setConfig;
  "config:setConfigBulk": typeof setConfigBulk;
  "dynamicIcon:setBadgeCount": typeof setBadgeCount;
  "loader:setAutoLaunchState": typeof setAutoLaunchState;
  "messageEncryption:cycleThroughPasswords": typeof cycleThroughPasswords;
  "mods:updateModsFull": typeof updateModsFull;
  "settings:createSettingsWindow": typeof createSettingsWindow;
  "settings:hotreloadLocale": typeof hotreloadLocale;
  "utils:saveFileToGCFolder": typeof saveFileToGCFolder;
  "venbind:isVenbindLoaded": typeof isVenbindLoaded;
  "venbind:setKeybinds": typeof setKeybinds;
  "venmic:stopVenmic": typeof stopVenmic;
}

export interface IpcOnChannels {
  "assetLoader:getAssets": typeof getAssets;
  "config:getConfig": typeof getConfig;
  "config:getConfigBulk": typeof getConfigBulk;
  "config:getDefaultValue": typeof getDefaultValue;
  "localization:i": typeof i;
  "messageEncryption:decryptMessage": typeof decryptMessage;
  "messageEncryption:encryptMessage": typeof encryptMessage;
  "utils:decryptSafeStorage": typeof decryptSafeStorage;
  "utils:encryptSafeStorage": typeof encryptSafeStorage;
  "utils:getDisplayVersion": typeof getDisplayVersion;
  "utils:getVersion": typeof getVersion;
  "utils:isEncryptionAvailable": typeof isEncryptionAvailable;
}

export interface RegisteredIpcHandleChannels {
  "flashTitlebar": (color: string) => void;
  "flashTitlebarWithText": (color: string, text: string) => void;
  "invidiousConfigChanged": () => void;
  "openFolder": (folder: string) => void;
  "window:Close": () => void;
  "window:Hide": () => void;
  "window:IsMaximized": () => void;
  "window:Maximize": () => void;
  "window:Minimize": () => void;
  "window:Show": () => void;
  "window:Unmaximize": () => void;
}

export interface RegisteredIpcOnChannels {
}

export type AllIpcHandleChannels = IpcHandleChannels & RegisteredIpcHandleChannels;
export type AllIpcOnChannels = IpcOnChannels & RegisteredIpcOnChannels;
export type AllIpcChannels = AllIpcHandleChannels & AllIpcOnChannels;

export type IpcHandleChannel = keyof AllIpcHandleChannels;
export type IpcOnChannel = keyof AllIpcOnChannels;
export type IpcChannel = keyof AllIpcChannels;

export type IpcParams<T extends IpcChannel> = Parameters<AllIpcChannels[T]>;
export type IpcReturn<T extends IpcChannel> = ReturnType<AllIpcChannels[T]>;

// Utility type for awaited return values
export type IpcReturnAwaited<T extends IpcChannel> = Awaited<IpcReturn<T>>;
