const fs = require('fs');
const path = require('path');

const jsonData = JSON.parse(fs.readFileSync(path.join(__dirname, "..", "assets", "lang", "en-US.json"), 'utf8'));

const result = {};

result["TEST"] = "This was autogenerated by assetsDev/genTestLanguage.js";

for (const setting in jsonData) {
    result[setting] = "💥";
}

fs.writeFileSync(path.join(__dirname, "..", "assets", "lang", "test-TEST.json"), JSON.stringify(result, null, 2), 'utf8');

console.log('Generated test language');